=== timliebhaber/sopra23_ai_contest/BotC_Ai/Schemas/config/boardConfig.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "title": "boardconfig schema",
  "type": "object",
  "required": [
    "name",
    "height",
    "width",
    "startFields",
    "checkPoints",
    "eye",
    "holes",
    "riverFields",
    "walls",
    "lembasFields",
    "eagleFields"
  ],
  "properties": {
    "name": {
      "type": "string",
      "minLength": 1
    },
    "height": {
      "type": "integer",
      "minimum": 2
    },
    "width": {
      "type": "integer",
      "minimum": 2
    },
    "startFields": {
      "type": "array",
      "minItems": 2,
      "maxItems": 6,
      "items": {
        "required": [
          "position",
          "direction"
        ],
        "properties": {
          "position": {
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
              "type": "integer"
            }
          },
          "direction": {
            "type": "string",
            "enum": [
              "NORTH",
              "SOUTH",
              "WEST",
              "EAST"
            ]
          }
        },
        "additionalProperties": false
      }
    },
    "checkPoints": {
      "type": "array",
      "minItems": 2,
      "items": {
        "type": "array",
        "minItems": 2,
        "maxItems": 2,
        "items": {
          "type": "integer"
        }
      }
    },
    "eye": {
      "required": [
        "position",
        "direction"
      ],
      "properties": {
        "position": {
          "type": "array",
          "minItems": 2,
          "maxItems": 2,
          "items": {
            "type": "integer"
          }
        },
        "direction": {
          "type": "string",
          "enum": [
            "NORTH",
            "SOUTH",
            "WEST",
            "EAST"
          ]
        }
      },
      "additionalProperties": false
    },
    "holes": {
      "type": "array",
      "items": {
        "type": "array",
        "minItems": 2,
        "maxItems": 2,
        "items": {
          "type": "integer"
        }
      }
    },
    "riverFields": {
      "type": "array",
      "items": {
        "required": [
          "position",
          "direction"
        ],
        "properties": {
          "position": {
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
              "type": "integer"
            }
          },
          "direction": {
            "type": "string",
            "enum": [
              "NORTH",
              "SOUTH",
              "WEST",
              "EAST"
            ]
          }
        },
        "additionalProperties": false
      }
    },
    "walls": {
      "type": "array",
      "items": {
        "type": "array",
        "items": {
          "type": "array",
          "minItems": 2,
          "maxItems": 2,
          "items": {
            "type": "integer"
          }
        }
      }
    },
    "lembasFields": {
      "type": "array",
      "items": {
        "required": [
          "position",
          "amount"
        ],
        "properties": {
          "position": {
            "type": "array",
            "minItems": 2,
            "maxItems": 2,
            "items": {
              "type": "integer"
            }
          },
          "amount": {
            "type": "integer"
          }
        },
        "additionalProperties": false
      }
    },
    "eagleFields": {
      "type": "array",
      "items": {
        "type": "array",
        "minItems": 2,
        "maxItems": 2,
        "items": {
          "type": "integer"
        }
      }
    }
  },
  "additionalProperties": false
}

=== timliebhaber/sopra23_ai_contest/BotC_Ai/Utils/boardconfigSelectCardsTest2.json
{
  "name": "THE CENTERLAEND",
  "height": 10,
  "width": 10,
  "startFields": [
    {
      "position": [3, 9],
      "direction": "NORTH"
    },
    {
      "position": [4, 8],
      "direction": "NORTH"
    },
    {
      "position": [5, 8],
      "direction": "NORTH"
    },
    {
      "position": [6, 9],
      "direction": "NORTH"
    }
  ],
  "checkPoints": [
    [0, 0],
    [9, 9]
  ],
  "eye": {
    "position": [4, 9],
    "direction": "NORTH"
  },
  "holes": [
    [3, 4],
    [6, 3]
  ],
  "riverFields": [
    {
      "position": [1, 2],
      "direction": "EAST"
    },
    {
      "position": [1, 3],
      "direction": "EAST"
    },
    {
      "position": [1, 4],
      "direction": "EAST"
    },
    {
      "position": [1, 5],
      "direction": "EAST"
    },
    {
      "position": [1, 6],
      "direction": "EAST"
    }
  ],
  "walls": [
    [
      [0, 5], [1, 5]
    ],
    [
      [1, 1], [2, 1]
    ],
    [
      [2, 1], [2, 2]
    ],
    [
      [4, 4], [5, 4]
    ],
    [
      [4, 6], [4, 7]
    ],
    [
      [5, 2], [5, 3]
    ],
    [
      [5, 6], [5, 7]
    ],
    [
      [7, 9], [8, 9]
    ]
  ],
  "lembasFields": [
    {
      "position": [0, 9],
      "amount": 6
    },
    {
      "position": [9, 0],
      "amount": 6
    }
  ],
  "eagleFields": [
    [1, 1],
    [9, 9],
    [9, 1]
  ]
}
